// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFqfqIlICrkNnbK5_zYYv9RAqzLMXap7c',
    appId: '1:394581004334:web:70b79ad52d9625ef35cfbf',
    messagingSenderId: '394581004334',
    projectId: 'moovly-9b6e3',
    authDomain: 'moovly-9b6e3.firebaseapp.com',
    storageBucket: 'moovly-9b6e3.firebasestorage.app',
    measurementId: 'G-FWHJKW01TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTT8iKn824T2KJV928O_s0YCLg11_WjqE',
    appId: '1:394581004334:android:2a1d27c58b72e7a635cfbf',
    messagingSenderId: '394581004334',
    projectId: 'moovly-9b6e3',
    storageBucket: 'moovly-9b6e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8eKLoocN3pcifOwsWJAFthYaWWkdgklM',
    appId: '1:394581004334:ios:b998cb7e19a87c6e35cfbf',
    messagingSenderId: '394581004334',
    projectId: 'moovly-9b6e3',
    storageBucket: 'moovly-9b6e3.firebasestorage.app',
    iosBundleId: 'com.example.moovly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8eKLoocN3pcifOwsWJAFthYaWWkdgklM',
    appId: '1:394581004334:ios:b998cb7e19a87c6e35cfbf',
    messagingSenderId: '394581004334',
    projectId: 'moovly-9b6e3',
    storageBucket: 'moovly-9b6e3.firebasestorage.app',
    iosBundleId: 'com.example.moovly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFqfqIlICrkNnbK5_zYYv9RAqzLMXap7c',
    appId: '1:394581004334:web:131f6d70e17d40f135cfbf',
    messagingSenderId: '394581004334',
    projectId: 'moovly-9b6e3',
    authDomain: 'moovly-9b6e3.firebaseapp.com',
    storageBucket: 'moovly-9b6e3.firebasestorage.app',
    measurementId: 'G-M8FTHXCL2S',
  );
}
